compile: avoid min macro pollution
The generic min macro in util.h is too common and can conflict with
other libraries. use ccan/minmax in the source files to avoid pollution.

Before renaming the macro, the cpp's std::min will fail to compile.
```
./test/cpp.cc: In function ‘int min_compile_test()’:
../src/nvme/util.h:563:19: error: expected unqualified-id before ‘(’ token
  563 | #define min(x, y) ((x) > (y) ? (y) : (x))
```

Signed-off-by: Jian Zhang <zhangjian.3032@bytedance.com>